apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb-pod
  template:
    metadata:
      labels:
        app: influxdb-pod
    spec:
      containers:
        - name: influxdb-deployment
          image: influxdb_image
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: influxdb-volume
              mountPath: /var/lib/influxdb
      volumes:
        - name: influxdb-volume
          persistentVolumeClaim:
            claimName: influxdb-pv-claim

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  type: ClusterIP
  selector:
    app: influxdb-pod
  ports:
    - port: 8086
      targetPort: 8086
      name: influxdb-port
