apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-pod
  template:
    metadata:
      labels:
        app: phpmyadmin-pod
    spec:
      containers:
        - name: phpmyadmin-deployment
          image: phpmyadmin_image
          imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin-pod
  ports:
    - port: 5000
      targetPort: 5000
      name: pma-port
